name: Change Issue Status

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to test'
        required: false
        default: '1'

jobs:
  update-linked-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      # Generate GitHub App token
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: nishmr22
          repositories: origin-22

      # Debug token
      - name: Debug Token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          TOKEN="${{ steps.generate_token.outputs.token }}"
          echo "Generated token: $(echo "$TOKEN" | cut -c 1-10)..."
          echo "Token length: ${#TOKEN}"
          export GH_TOKEN="$TOKEN"
          echo "Test repo access:"
          gh api repos/nishmr22/origin-22 --jq '.full_name'

      # Run custom action
      - name: Check all PRs with linked issues and update status
        uses: ./.github/actions/pr_linked/update_linked_issue_status
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}